### ISSUE TITLE
HacktoberFest PR Not Consider

### ISSUE THREAD

**Issue by KevinMathewTh** [helios1101/HacktoberFest_20#329]
**Is your feature request related to a problem? Please describe.**
The contribution are not contributing the PR count for hactoberfest 2020

**Describe the solution you'd like**
Addition of the label hacktoberfest to the repo will fix this

**Describe alternatives you've considered**
There are no alternatives , refer to the new guidlines for HacktoberFest2020

**Comment by helios1101** [comment]
Hi @KevinMathewTh !
We aim to provide ice buster start, that helps people clear their queries before making any vaid contributions.
Our aim is to uplift the beginners by teaching right way, and not guarantee the tshirts. 
Hope you had a gala time making the PR.

Keep safe :)
